# App
spring.application.name=gamecoach

# Riot API
riot.api.key=YOUR_KEY_HERE
riot.region=la1

# Groq
groq.api.key=YOUR_KEY_HERE
groq.model=llama-3.3-70b-versatile
groq.api.url=https://api.groq.com/openai/v1/chat/completions